query getAlbums($page: Int, $limit: Int) {
  albums(options: { paginate: { page: $page, limit: $limit } }) {
    data {
      id
      title
      user {
        id
        username
      }
      photos {
        data {
          id
        }
      }
    }
    meta {
      totalCount
    }
  }
}
